### PR TITLE
Fix young metric

### PR DESCRIPTION
**Pull request by Thalos12**
This change is necessary to take into account the effect of crowding.

Main changes:
- use `rubin_sim.maf.metrics.crowdingMetric.CrowdingM5Metric` to get crowding depth
- take depth as minimum between m5 and crowding depths
- optionally return distance corresponding to depth if the `returnDistance` keyword argument is set to True

### CODE REVIEW

**Review by rhiannonlynne — COMMENTED** [review]
This looks reasonable, and I'll double check that it works for us shortly. 
Given the timing with the SCOC review, I don't think we can get this in place for that evaluation unfortunately. (rerunning on all of the older simulations would be intensive). 
However, we can certainly run a few of the newer simulations with this new version to look at how much it changes the results.

**Comment by Thalos12** [comment]
It is my fault, I made the pull request later than I intended to, but I think it would be great if the metric could be run on the newer simulations at least. Thank you!

**Review by rhiannonlynne — APPROVED** [review]

**Comment by rhiannonlynne** [comment]
Approve, but I guess we should merge this to the new dev-camel-snake branch (after appropriate updates) instead. 
Also, the file changed needs "black" to be run on it, as it's failing tests due to that.

**Comment by Thalos12** [comment]
Thank you very much for merging the pull request.

Apologies for not running black on the code, I will remember to do it before a making a pull request next time.

**Pull request merged**
