### PR TITLE
Updated metrics for Galactic Plane Survey

### PR DESCRIPTION
**Pull request by rachel3834**
This PR includes the metrics proposed for the Galactic Plane and Magellanic Clouds minisurvey (as described in the corresponding Metric Package document https://docs.google.com/document/d/1tzjHtftqV_9wReJYi_jm9YX8w2gtt4XwJUphFVqPgoo/edit?usp=sharing). 
The metrics have been revised to account for feedback from Lynne & Peter at the 2nd SCOC workshop.

### CODE REVIEW

**Comment by tribeiro** [comment]
Hi @rachel3834 , thank you so much for the PR! 

We recently adopted [black](https://black.readthedocs.io/) format for rubin_sim. 

This makes the code easier to read, review and maintain.

Do you mind trying to reformatting your code with it?

We are currently using black 20.8b1. You can install it with conda by doing:

```
conda install black=20.8b1
```

Then, to reformat your code simply do:

```
cd <path-to>/rubin_sim/
black .
```

Let me know if you need any help!

**Comment by rachel3834** [comment]
Thanks Tiago; I've now run the formatter.

**Comment by rhiannonlynne** [comment]
Hi Rachel, 

Another request, that I think was perhaps is based on some poor directions from us somewhere (because I've seen others doing it too). 

Could you please remove the galactic plane priority maps from this PR, and just point us to a place to download them instead? (Or attach them to the PR). 
We can put them into the $RUBIN_SIM_DATA download, but I would prefer not to have them directly in the repository. 
To access this information from within your metric, you would then find their location by doing :

```
import os
from rubin_sim.data import get_data_dir

galactic_plane_map = 'GalacticPlanePriorityMap_g.fits' (or whatever the file name is)
galactic_plane_priority_mapfile = os.path.join(get_data_dir(), 'maf', galactic_plane_map)
```

If you have a unit test (yay!!)which depends on having the maps, let me know and I can add the files to the MAF data right away so that the GitHub actions tests will be able to access those and use them.

**Comment by rachel3834** [comment]
OK, I've made those changes and removed the map data.  You can download those data from https://github.com/LSST-TVSSC/software_tools/tree/main/footprint_maps instead.  

I'm afraid I don't have a unittest (though I would normally) because it wasn't clear to me how to implement one within the MAF.   The ...maf/metrics/test directory contains the .npz output from the notebooks I've been using as a substitute and I didn't want to submit those.  I'm happy to write one if you let me know how you prefer them to be implemented.

**Comment by rhiannonlynne** [comment]
I created a branch to merge this PR into, so I can fix up some of the failing tests and make some other small modifications. I'll tag you back @rachel3834 when it's ready.

**Pull request merged**
