### PR TITLE
Add XRB Outburst metric

### PR DESCRIPTION
**Pull request by ebellm**
This PR adds a new X-ray binary outburst metric to `mafContrib`.

One new data file is needed in $RUBIN_SIM_DATA_DIR/maf/xrb : it can be downloaded from [this link](https://drive.google.com/file/d/1z7DICvqhbkX-rne-E2ppsvNbFkOBcIWl/view?usp=sharing).

[This notebook](https://github.com/lsst/rubin_sim_notebooks/blob/u/ebellm/xrb_outburst_metric/maf/science/XRB_Metric.ipynb) shows the metric in use as well as some analysis on the baseline sim.  I will make a PR to `rubin_sim_notebooks` for it as well.

### CODE REVIEW

**Review by yoachim — APPROVED** [review]
Looks good to me.

**Comment by ebellm** [comment]
Hi @yoachim, did you grab the data file above for `RUBIN_SIM_DATA_DIR`?  I'm not seeing it when running `rs_download_data`.  Thanks!

**Comment by yoachim** [comment]
> 

@ebellm, should be in there. I think `rs_download_data` won't clobber things, so you need to delete your old maf data directory first to get the latest version of everything.

**Comment by yoachim** [comment]
Oh, if I read my own documentation I could have told your you have to use the `rs_download_data --force` to update.

**Pull request merged**
