### PR TITLE
OPSIM-1155: Update DDF metrics / metric_subsets

### PR DESCRIPTION
**Pull request by rhiannonlynne**
In preparation for making a summary for the DDF working group, this PR 
* changes the name of "metric_set" to "metric_subset" 
* adds a Coaddm5PerNight metric
* supports UniSlicers being run with metrics which return a Histogram (object) value (because UniSlicers automatically have IdentityMetric added in order to add results to the summary database)
* Allows UniSlicers to carry slicePoint information (such as identifying the RA/Dec of a DDF location)
* Modifies an option for plotting with the OneDSlicer to permit accurate plotting of data with filled data values
* Quiets voluminous warnings about bin size from the "automatic bin size calculation utility"
* Updates DDF metrics to add CoaddM5PerNight. Also modifies some other cadence 'per night' metrics to run "Per DDF" instead of "at the center of the DDF" (i.e. using a UniSlicer + sql constraint, instead of UserPointSlicer at the center of the DDF).

### CODE REVIEW

**Comment by rhiannonlynne** [comment]
I guess this is likely to fail unit tests until we make a new tag for rubin_scheduler (to add the "get_current_footprint" function)

**Comment by rhiannonlynne** [comment]
Ok - I needed to update the data download for MAF to add the metric_subsets.json file and a small h5 summary stat test file. 
At the same time, I added the data file for Eli's photometric calibration metric, so that'll be the next PR I think. 
Rubin-scheduler has been tagged so the get_current_footprint utility should be available. 
Let's see if there's anything else missing between dev and this environment.

**Review by yoachim — APPROVED** [review]
Looks all reasonable.

Seems like there's a `tests_2024_04_23.tgz` file that got created but isn't being used. We should update to using that one or delete it off sdf to avoid confusion.

**Comment by rhiannonlynne** [comment]
Thanks - I thought the tests had been updated at some point, but I was just going with what was in the previous dictionary. Will update the tests to use the new version (which just drops the skybrightnessPre files from the tests directory) and double-check.

**Pull request merged**
