### PR TITLE
Add metric to compute error in color due to crowding

### PR DESCRIPTION
**Pull request by knutago**
This metric adds the ability to compute the correlated noise in two bands due to crowding, so that science cases in the Galactic Plane and Magellanic Clouds may be properly evaluated.  It relies on joint luminosity functions computed from Leo Girardi's TRILEGAL model of the Galaxy, as available through datalab.noirlab.edu.  The joint LFs are stored in a Google drive folder here:
https://drive.google.com/drive/folders/1oblrD2qF7Kfi8ugQxrJg0V_SC8sQuIsP?usp=sharing

Am also issuing a PR to rubin_sim_notebooks with an example showing how to use the metric.

### CODE REVIEW

**Comment by rhiannonlynne** [comment]
Oh, sorry @knutago  - just saw this PR. Do the files in google drive you sent me correspond to this PR and I should add them to the maf data ? (is there a specific location?)

**Comment by knutago** [comment]
Hi Lynne -- sorry for my own slow reply!  Yes, those files from the Google drive go with this PR.  There is no particular location, but probably should specify the location where they end up in the __init__ of the two classes.  Currently the default value is  lfpath='~/lsst/SMWLV-metrics.orig/', which is where I had it to make the example notebook run.

**Comment by knutago** [comment]
The other linked PR is this one: https://github.com/lsst/rubin_sim_notebooks/pull/31

**Comment by rhiannonlynne** [comment]
I'll open a new PR to merge this branch into rubin_sim lsst:main shortly (after pulling in the maps, running black, etc.)

**Pull request merged**
