### PR TITLE
U/yoachim/goodseeing2

### PR DESCRIPTION
**Pull request by yoachim**
Add a basis function so we can include a desire to collect images in good seeing conditions.

### CODE REVIEW

**Comment by ehneilsen** [comment]
Are we trying to move to following PEP8 naming conventions? It looks like the new changes are consistent with current usage in rubin_sim, but quite far from PEP8, which specifies that classes are all CapsCase (words capitalized, no underscores), while variables, methods and function names are all snake_case (no capitals, words separated by underscores). Whether this is a problem or not just depends on what we want to do. Personally, I find our failure to follow the normal conventions makes the code harder to read.

**Comment by ehneilsen** [comment]
Do we intend to specify a number of visits with delivered seeing better than some value, or a number of visits taken when the zenith seeing is better than some value? I'm not sure, but it looks like the code does the former, but the latter is probably what we want. I don't think we want to observe a field at high airmass because we need a good seeing image of that field, and the zenith seeing is better than the cutoff.  Cutting on the atmospheric seeing will work most of the time, because either the high airmass won't push it over the limit or the field is at low airmass anyway, but I expect that sometimes it will be important.

**Comment by yoachim** [comment]
Yeah, the plan is we'll go through and fix the naming conventions. I think going though and doing it in a massive change will be better than piecemeal. 

The `conditions.FWHMeff` is a HEALpix map of the seeing at each healpixel including filter and airmass info, so it's not going to accidentally go to high airmass just because the zenith seeing is good.

**Review by ehneilsen — APPROVED** [review]

**Comment by tribeiro** [comment]
Please, rebase before merging to main!

**Pull request merged**
