### PR TITLE
Fix selection of labels to signify inversion in metric/run mesh plots

### PR DESCRIPTION
**Pull request by ehneilsen**
Sometimes, the old code modified the metric labels of the wrong metrics to reflect inversion.

### CODE REVIEW

**Comment by ehneilsen** [comment]
Don't approve this merge quite yet; now that I fixed the test, I need to do a rebase.

**Comment by rhiannonlynne** [comment]
Ah I see the problem you were solving with the initial PR (about the inversion of metric labels) - more along the lines of if there were multiple metrics with the same name in the metric_set then it was a problem.  I  was curious, as I hadn't seen it go wrong anywhere. 

I had been having the "multiple metrics with the same name" issue, though, and just solving it by removing the duplicates before sending in the 'metric set'. This will be cleaner - nice fix.

**Comment by rhiannonlynne** [comment]
As far as testing for the specific file instead of the directory .. it's a little more brittle in case we change the filenames or default nside (and then removed nside=32) for some reason. However, it is also a more specific test and those are unlikely scenarios, so seems reasonable to me as well.

**Comment by ehneilsen** [comment]
I think something went wrong in a conda dependency. Nothing that changed since the last time it passed seems at all related to the failure, and it’s failed like this twice today.
________________________________

**Comment by ehneilsen** [comment]
I switched to using the specific file rather than the directory, because checking for the directory didn't actually work. It looks like the directory itself is actually created in the tests, so testing for the directory doesn't skip the tests.

From: Lynne Jones ***@***.***>
Reply-To: lsst/rubin_sim ***@***.***>
Date: Tuesday, March 7, 2023 at 2:02 PM
To: lsst/rubin_sim ***@***.***>
Cc: "Eric H Neilsen Jr." ***@***.***>, Author ***@***.***>
Subject: Re: [lsst/rubin_sim] Fix selection of labels to signify inversion in metric/run mesh plots (PR #287)


As far as testing for the specific file instead of the directory .. it's a little more brittle in case we change the filenames or default nside (and then removed nside=32) for some reason. However, it is also a more specific test and those are unlikely scenarios, so seems reasonable to me as well.

**Comment by ehneilsen** [comment]
The fix wasn't only about dealing with duplicates: in the old way, I was seeing the wrong labels get modified even when there weren't duplicates. Duplicates were also a problem, though.

**Comment by rhiannonlynne** [comment]
I asked about the failure on the #dm-conda channel. 
I think it's a conda-forge migration from jpeg to jpegturbo that's happening and is causing some issues. 

It builds in Jenkins, so I think you can probably just go ahead and merge. This isn't a problem at our end, and unless people are building the environment from scratch, it won't be a problem for them either.

**Review by rhiannonlynne — APPROVED** [review]

**Pull request merged**
