### PR TITLE
Restore setup_requires in setup.py

### PR DESCRIPTION
**Pull request by tribeiro**

### CODE REVIEW

**Review by yoachim — APPROVED** [review]

**Comment by rhiannonlynne** [comment]
Hi Tiago - looks like you're removing the setup requires from the setup.py file? 
That line was added by @beckermr to enable setuptools_scm to be included in the git archive tarballs. 
Is it causing problems with the builds in the lsst-ts Jenkins?

**Comment by tribeiro** [comment]
I am actually adding a line that was removed

**Comment by tribeiro** [comment]
Yes, it's causing the conda build to fail

**Comment by rhiannonlynne** [comment]
I'm super confused. Matt's PR looked like it *added* that line?

**Comment by tribeiro** [comment]
let me see if I can find a way to co-exist this with the conda build...

**Comment by tribeiro** [comment]
> I'm super confused. Matt's PR looked like it _added_ that line?

Yes, you are right sorry...

**Comment by beckermr** [comment]
add `setuptools_scm_git_archive` into your env

I should have done that. Sorry!

**Comment by rhiannonlynne** [comment]
@tribeiro - @beckermr is setting up a Conda-forge build of rubin_sim https://github.com/conda-forge/staged-recipes/pull/17146/files

**Comment by tribeiro** [comment]
It is part of the conda package dependency but not as a "setup dependency".. I think I can fix it by adding it as a setup dependency.. hold on

**Comment by beckermr** [comment]
see here: https://github.com/lsst/rubin_sim/pull/94

**Comment by tribeiro** [comment]
I'm closing this PR.. I'll patch the conda recipe to add this new dependency...

**Comment by rhiannonlynne** [comment]
Sorry about the unexpected change, Tiago. I didn't realize it would crash the lsst-ts conda builds, and while I can see if they fail, I don't have much transparency into why they're failing (at least in this case). 
Longer term, DM hosts all of its packages on conda-forge and I suspect that's where system performance packages would end up if they're conda-installable .. keeping two channels/packages open is fine, and might be a super reasonable course of action so that you can run the unit tests in the lsst-ts environment (which I think you're doing?).

@beckermr here is where I think the lsst-ts conda recipe can be found: 
https://github.com/lsst-ts/ts_recipes/blob/develop/rubin-sim/conda/meta.yaml

**Comment by tribeiro** [comment]
No problem at all!

I think we can retire the tssw build once we have it on conda-forge...

**Comment by beckermr** [comment]
Yeah that recipe is wrong anyways. It vendors setup time deps

**Comment by tribeiro** [comment]
@beckermr , what do you mean?

**Comment by beckermr** [comment]
Ack I was wrong. Sorry!

**Comment by beckermr** [comment]
This package is on conda-forge now, so feel free to pull from there.

**Comment by tribeiro** [comment]
Nice! thank you!

**Pull request closed without merging**
